import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_FLEET_SAMPLE_SIZE = 10;
const REGRESSION_OUTPUT_DIRECTORY_NAME = ".regression";
const REACT_REVIEW_API_RELATIVE_PATH = "Developer/react-review/apps/api";

const REGRESSION_FLEET: readonly string[] = [
  "pierrecomputer/pierre",
  "aidenybai/react-grab",
  "aidenybai/bippy",
  "millionco/react-doctor",
  "millionco/same",
  "millionco/ami",
  "nisargio/scissors",
  "millionco/expect",
  "aidenybai/react-scan",
  "pingdotgg/t3code",
  "tldraw/tldraw",
  "excalidraw/excalidraw",
  "twentyhq/twenty",
  "makeplane/plane",
  "formbricks/formbricks",
  "PostHog/posthog",
  "supabase/supabase",
  "onlook-dev/onlook",
  "payloadcms/payload",
  "getsentry/sentry",
  "calcom/cal.com",
  "dubinc/dub",
  "nodejs/nodejs.org",
  "shadcn-ui/ui",
  "lobehub/lobe-chat",
  "langfuse/langfuse",
  "unkeyed/unkey",
  "triggerdotdev/trigger.dev",
  "baptisteArno/typebot.io",
  "medusajs/medusa",
  "appsmithorg/appsmith",
  "ToolJet/ToolJet",
  "RocketChat/Rocket.Chat",
  "RhysSullivan/executor",
  "better-auth/better-auth",
  "mastra-ai/mastra",
  "freeCodeCamp/freeCodeCamp",
  "facebook/create-react-app",
  "ChatGPTNextWeb/NextChat",
  "lobehub/lobehub",
  "grafana/grafana",
  "apache/superset",
  "toeverything/AFFiNE",
  "usememos/memos",
  "laurent22/joplin",
  "mastodon/mastodon",
  "penpot/penpot",
  "metabase/metabase",
  "AykutSarac/jsoncrack.com",
  "usebruno/bruno",
  "calcom/cal.diy",
  "nexu-io/open-design",
  "outline/outline",
  "Kong/insomnia",
  "LAION-AI/Open-Assistant",
  "drawdb-io/drawdb",
  "amruthpillai/reactive-resume",
  "mattermost/mattermost",
  "umami-software/umami",
  "Dokploy/dokploy",
  "hasura/graphql-engine",
  "conductor-oss/conductor",
  "CopilotKit/CopilotKit",
  "gitroomhq/postiz-app",
  "gethomepage/homepage",
  "bigint/hey",
  "onyx-dot-app/onyx",
  "jitsi/jitsi-meet",
  "t3-oss/create-t3-app",
  "nrwl/nx",
  "getredash/redash",
  "labring/FastGPT",
  "srbhr/Resume-Matcher",
  "SigNoz/signoz",
  "Infisical/infisical",
  "actualbudget/actual",
  "karakeep-app/karakeep",
  "responsively-org/responsively-app",
  "nocobase/nocobase",
  "chartdb/chartdb",
  "teableio/teable",
  "navidrome/navidrome",
  "readest/readest",
  "dyad-sh/dyad",
  "wulkano/Kap",
  "decaporg/decap-cms",
  "CapSoftware/Cap",
  "linkwarden/linkwarden",
  "bluesky-social/social-app",
  "signalapp/Signal-Desktop",
  "infinitered/reactotron",
  "apache/answer",
  "apitable/apitable",
  "midday-ai/midday",
  "streetwriters/notesnook",
  "vercel/commerce",
  "tinacms/tinacms",
  "element-hq/element-web",
  "documenso/documenso",
  "Automattic/wp-calypso",
  "alibaba/formily",
  "BasedHardware/omi",
  "illacloud/illa-builder",
  "openreplay/openreplay",
  "logto-io/logto",
  "plankanban/planka",
  "codexu/note-gen",
  "giscus/giscus",
  "wojtekmaj/react-pdf",
  "kusti8/proton-native",
  "elie222/inbox-zero",
  "reactide/reactide",
  "jhen0409/react-native-debugger",
  "blinkospace/blinko",
  "hackjutsu/Lepton",
  "woocommerce/woocommerce",
  "devhubapp/devhub",
  "polarsource/polar",
  "zuiidea/antd-admin",
  "InsForge/InsForge",
  "hyperdxio/hyperdx",
  "yang991178/fluent-reader",
  "berty/berty",
  "nhost/nhost",
  "gridstack/gridstack.js",
  "heyform/heyform",
  "BuilderIO/builder",
  "openstatusHQ/openstatus",
  "webstudio-is/webstudio",
  "xanderfrangos/twinkle-tray",
  "idurar/idurar-erp-crm",
  "Shopify/react-native-skia",
  "maotoumao/MusicFreeDesktop",
  "papermark/papermark",
  "relax/relax",
  "Snouzy/workout-cool",
  "dilanx/craco",
  "ajnart/homarr",
  "react-native-webview/react-native-webview",
  "yinxin630/fiora",
  "buildship-ai/rowy",
  "plasmicapp/plasmic",
  "hexclave/stack-auth",
  "software-mansion/react-native-gesture-handler",
  "nraiden/cofounder",
  "ganeshrvel/openmtp",
  "jpuri/react-draft-wysiwyg",
  "standardnotes/app",
  "Flagsmith/flagsmith",
  "OpenSignLabs/OpenSign",
  "sanity-io/sanity",
  "jvalen/pixel-art-react",
  "lightdash/lightdash",
  "Uniswap/interface",
  "czy0729/Bangumi",
  "Flipkart/recyclerlistview",
  "lingodotdev/lingo.dev",
  "AmanVarshney01/create-better-t-stack",
  "gitify-app/gitify",
  "benoitvallon/react-native-nw-react-calculator",
  "rcbyr/keen-slider",
  "edp963/davinci",
  "react-native-config/react-native-config",
  "mediacms-io/mediacms",
  "Expensify/App",
  "clidey/whodb",
  "streamlabs/desktop",
  "gitpoint/git-point",
  "sqlectron/sqlectron",
  "liveblocks/liveblocks",
  "oliverschwendener/ueli",
  "Yooooomi/your_spotify",
  "Bowen7/regex-vis",
  "rainbow-me/rainbow",
  "OHIF/Viewers",
  "outsourc-e/hermes-workspace",
  "prazzon/Flexbox-Labs",
  "chartbrew/chartbrew",
  "wojtekmaj/react-calendar",
  "iSimar/HackerNews-React-Native",
  "software-mansion/react-native-screens",
  "plouc/mozaik",
  "Pagedraw/pagedraw",
  "lbryio/lbry-desktop",
  "chaskiq/chaskiq",
  "React-Proto/react-proto",
  "MauriceNino/dashdot",
  "attentiveness/reading",
  "pashpashpash/vault-ai",
  "CherryHQ/cherry-studio-app",
  "Peppermint-Lab/peppermint",
  "creativetimofficial/material-dashboard-react",
  "fangpenlin/avataaars-generator",
  "MetaMask/metamask-mobile",
  "chrisvel/tududi",
  "microsoft/vscode-react-native",
  "edrlab/thorium-reader",
  "kentcdodds/bookshelf",
  "ohmplatform/FreedomGPT",
  "IceEnd/Yosoro",
  "batnoter/batnoter",
  "nz-m/SocialEcho",
  "adrianhajdin/aora",
  "RocketChat/Rocket.Chat.ReactNative",
  "OneKeyHQ/app-monorepo",
  "adrianhajdin/ecommerce_sanity_stripe",
  "running-elephant/datart",
  "Flaque/quirk",
  "wwayne/react-native-nba-app",
  "ammarahm-ed/react-native-actions-sheet",
  "BlackHatDevX/openspot-music-app",
  "martpie/museeks",
  "Matterwiki/Matterwiki",
  "catalinmiron/react-native-dribbble-app",
  "mohamedsamara/mern-ecommerce",
  "LucasBassetti/react-simple-chatbot",
  "stoneWeb/elm-react-native",
  "adrianhajdin/project_shareme_social_media",
  "birkir/prime",
  "Jellify-Music/App",
  "binaricat/Netcatty",
  "CaviraOSS/PageLM",
  "ed-roh/react-admin-dashboard",
  "learnhouse/learnhouse",
  "expo/react-native-action-sheet",
  "adrianhajdin/project_medical_pager_chat",
  "adrianhajdin/social_media_app",
  "growilabs/growi",
  "027xiguapi/pear-rec",
  "Raathigesh/dazzle",
  "seniv/react-native-notifier",
  "79E/ChatGpt-Web",
  "jgudo/ecommerce-react",
  "DeadWaveWave/opencove",
  "qiutongxue/oba-live-tool",
  "aws-samples/bedrock-chat",
  "storybookjs/react-native",
  "mb21/panwriter",
  "amicalhq/amical",
  "bangle-io/bangle-io",
  "KittyCAD/modeling-app",
  "Shpendrr/react-app-structure",
  "mariusandra/insights",
  "ed-roh/mern-social-media",
  "alishobeiri/thread-notebook",
  "JasonStu/ReactNative_Shopping",
  "estevanmaito/windmill-dashboard-react",
  "mCodex/react-native-sensitive-info",
  "r-park/todo-react-redux",
  "KieSun/Chat-Buy-React",
  "saleor/saleor-dashboard",
  "hasan-py/Hayroo",
  "Rabithua/Rote",
  "pupilfirst/pupilfirst",
  "raineroviir/react-redux-socketio-chat",
  "koolkishan/chat-app-react-nodejs",
  "777genius/agent-teams-ai",
  "chatwoot/chatwoot-mobile-app",
  "blueberrycongee/Lumina-Note",
  "fireship-io/react-firebase-chat",
  "jamaljsr/polar",
  "victoralvesf/aonsoku",
  "sahat/newedenfaces-react",
  "kizuna-ai-lab/sokuji",
  "victorbalssa/abacus",
  "zhufengketang/app",
  "shamahoque/mern-social",
  "kuwala-io/kuwala",
  "aws-samples/swift-chat",
  "LiuYuYang01/ThriveX-Blog",
  "shwosner/realtime-chat-supabase-react",
  "bukinoshita/taskr",
  "MrXujiang/next-admin",
  "letterpad/letterpad",
  "expo/orbit",
  "cometchat/cometchat-uikit-react-native",
  "C-JSN/D3-ID3",
  "anisul-Islam/react-assignment-1-products-listing-app",
  "cometchat/cometchat-uikit-react",
  "TeXlyre/texlyre",
  "Ohh-889/skyroc-admin",
  "unigraph-dev/unigraph-dev",
  "CromwellCMS/Cromwell",
  "KSJaay/Lunalytics",
  "ftzi/react-native-shadow-2",
  "hitarth-gg/zenshin",
  "heylinda/heylinda-app",
  "awehook/blink-mind-desktop",
  "RameshMF/ReactJS-Spring-Boot-CRUD-Full-Stack-App",
  "tsurupin/portfolio",
  "BradGroux/veritas-kanban",
  "transmute-app/transmute",
  "EkiZR/Portofolio_V5",
  "functionland/fx-fotos",
  "dharness/react-chat-window",
  "Sherlockouo/music",
  "adrianhajdin/react_native-restate",
  "yoonic/nicistore",
  "songxiaoliang/ReactNativeApp",
  "bndkt/react-native-app-clip",
  "WJZ-P/TFT-Hextech-Helper",
  "misa-j/social-network",
  "overlayeddev/overlayed",
  "bbplayer-app/BBPlayer",
  "sneljo1/auryo",
  "nguymin4/react-videocall",
  "Grashjs/cmms",
  "nfl/react-metrics",
  "febobo/react-native-redux-FeInn",
  "fireyy/react-antd-admin",
  "nelsonkuang/ant-admin",
  "rgommezz/react-native-chatgpt",
  "nikunjsingh93/react-glass-keep",
  "unvalley/ephe",
  "safe-global/safe-wallet-monorepo",
  "lionsharecapital/lionshare-desktop",
  "ltadpoles/react-admin",
  "santifer/cv-santiago",
  "RARgames/4gaBoards",
  "southliu/south-admin-react",
  "mrktsm/codecafe",
  "crisanlucid/vite-react-tailwind-bionic-reading",
  "creativetimofficial/purity-ui-dashboard",
  "NiceDash/Vibe",
  "DLand-Team/moderate-react-admin",
  "netbirdio/dashboard",
  "api-platform/admin",
  "f/agentlytics",
  "clawwork-ai/ClawWork",
  "Brainfock/Brainfock",
  "biaochenxuying/blog-react-admin",
  "creativetimofficial/black-dashboard-react",
  "LinMoQC/Memory-Blog",
  "SolidZORO/leaa",
  "walljser/cms_community_e_commerce",
  "open-source-labs/ReacType",
  "creativetimofficial/argon-dashboard-react",
  "phongna07/fireverse",
  "creativetimofficial/material-tailwind-dashboard-react",
  "picturama/picturama",
  "rock-solid/pwa-theme-woocommerce",
  "lucavallin/verto",
  "sqlrooms/sqlrooms",
  "soroushchehresa/unsplash-wallpapers",
  "Justin-lu/react-redux-antd",
  "itzpradip/react-native-firebase-social-app",
  "LanceMoe/openai-translator",
  "RavelloH/NeutralPress",
  "alextselegidis/plainpad",
  "mihir0699/Video-Chat",
  "computing-den/unforget",
  "ketchuphq/ketchup",
  "wangrongding/wallpaper-box",
  "JSLancerTeam/crystal-dashboard",
  "bluedaniel/Kakapo-app",
  "merikbest/ecommerce-spring-reactjs",
  "namespace-ee/upcount",
  "moollaza/repo-remover",
  "SuperViz/superviz",
  "levelopers/Ecommerce-Reactjs",
  "davehowson/chat-app",
  "quintuslabs/fashion-cube",
  "lvwangbeta/Poplar",
  "Xtrendence/Cryptofolio",
  "mvdicarlo/postybirb",
  "proshoumma/Mister-Poster",
  "CodeWithHarry/iNotebook-React",
  "seenaburns/isolate",
  "Cezerin2/Cezerin2",
  "ErickKS/vite-deploy",
  "tinode/webapp",
  "ujjavaldesai07/spring-boot-react-ecommerce-app",
  "goshacmd/pabla",
  "lydiahallie/React-Ecommerce",
  "patrick-michelberger/serverless-shop",
  "dhatGuy/PERN-Store",
  "dxx/mango-music",
  "z-9527/admin",
  "elbwalker/walkerOS",
  "yeahhe365/Prisma",
  "Fanzzzd/repo-wizard",
  "rocketseat-education/nlw-expert-react",
  "inovex/scrumlr.io",
  "abahmed/Deer",
  "jrussbautista/dress-shop",
  "creativetimofficial/soft-ui-dashboard-react",
  "software-mansion-labs/react-native-rag",
  "Beever-AI/beever-atlas",
  "earthcomfy/lets-chat",
  "veyliss/ai-localbase",
  "DaiYz/react-native-easy-chat-ui",
  "Bourhjoul/Mern-Ecommerce-website",
  "LeDat98/NexusRAG",
  "1ven/do",
  "jotyy/Mantine-Admin",
  "Levix0501/notra",
  "sanjeevyadavIT/magento_react_native",
  "ZahraMirzaei/online-shop",
  "DefiLlama/defillama-app",
  "machadop1407/react-socketio-chat-app",
  "arifszn/ezfolio",
  "leemonade/leemons",
  "schneidmaster/socializer",
  "betaacid/expo-analytics",
  "basementstudio/commerce-toolkit",
  "raj074/mern-social-media",
  "kaloraat/react-node-ecommerce",
  "mohammadoftadeh/next-ecommerce-shopco",
  "Syncano/syncano-dashboard",
  "Rajatm544/MERN-Blog-App",
  "LiuYuYang01/ThriveX-Admin",
  "TheCoderDream/React-Ecommerce-App-with-Redux",
  "meilisearch/mini-dashboard",
  "kamjin3086/chatless",
  "papercups-io/chat-widget",
  "design-sparx/antd-multipurpose-dashboard",
  "stephensanwo/fullstack-ai-chatbot",
  "DanialK/ReactJS-Realtime-Chat",
  "funador/react-auth-client",
  "ecency/ecency-mobile",
  "nusr/excel",
  "stuyy/chat-platform-react",
  "baimingxuan/react-admin-design",
  "bmcmahen/toasted-notes",
  "burakorkmez/react-admin-dashboard",
  "danloh/mdSilo-web",
  "baiwumm/react-admin",
  "ed-roh/react-ecommerce",
  "seawind8888/Nobibi",
  "enatega/shopping-cart-ecommerce",
  "dabit3/heard",
  "composify-js/composify",
  "stellar/dashboard",
  "burdy-io/burdy",
  "walljser/community_e_commerce",
  "Ujjalzaman/Easy-Consulting-react",
  "andrewcoelho/react-text-editor",
  "trananhtuat/tua-react-admin",
  "ZainRk/React-Admin-Dashboard-public",
  "creativetimofficial/paper-dashboard-react",
  "ele828/leanote-ios-rn",
  "yTakkar/React-Mini-Social-Network",
  "MrXujiang/XPCMS",
  "adrianhajdin/travel-agency-dashboard",
  "converge/instapy-dashboard",
  "inifarhan/skaters",
  "acmerobotics/ftc-dashboard",
  "taniarascia/chat",
  "OpenBeta/open-tacos",
  "liuguanhua/react-antd-admin",
  "elibenjii/ecommerce-react",
  "bkywksj/knowledge-base",
  "loveRandy/react-admin",
  "bidah/universal-medusa",
  "creativetimofficial/muse-ant-design-dashboard",
  "zeus-12/uxie",
  "seanmiller802/BrowserTime",
  "ensdomains/ens-app-v3",
  "yonatanmgr/mathberet",
  "llorentegerman/react-admin-dashboard",
  "j471n/j471n.in",
  "praveen-sripati/nexus",
  "coderdost/MERN-ecommerce-Frontend",
  "boluo2077/deep-rag",
  "satnaing/satnaing.dev",
  "Bereky/mern-ecommerce",
  "bldrs-ai/Share",
  "alexindigo/ndash",
  "ruppysuppy/Pizza-Man",
  "jeandv/jeanrondon.dev",
  "eminbasbayan/full-stack-e-commerce",
  "developer-junaid/DeveloperFolio",
  "creativetimofficial/vision-ui-dashboard-react",
  "e2b-dev/dashboard",
  "betterlytics/betterlytics",
  "Skyfay/SkySend",
  "ajaybor0/MERN-eCommerce",
  "focallocal/fl-maps",
  "rahulsahay19/Java-React-FullStack",
  "betomoedano/ChatApp",
  "ButterCMS/react-cms-blog-with-next-js",
  "john-smilga/react-phone-e-commerce-project",
  "kriziu/collabio",
  "Timonwa/react-chat",
  "chenjun1127/react-antd-admin",
  "creativetimofficial/now-ui-dashboard-react",
  "AdamNowotny/BuildReactor",
  "guyariely/noteworthy",
  "creativetimofficial/nextjs-argon-dashboard",
  "prabinmagar/dashboard-ui-with-reactjs",
  "pattjoshi/Multi_vondor_E_shop",
  "taskrabbit/react-native-zendesk-chat",
  "Morelitea/initiative",
  "Saurabh-8585/MERN-E-Commerce-Frontend",
  "ConnectyCube/connectycube-reactnative-samples",
  "0mar-helal/multimart-react-ecommerce",
  "PierreCapo/react-native-socials",
  "mudzikalfahri/wefootwear-store",
  "ElSierra/Social-app-React-Native",
  "unrealmanu/ga-4-react",
  "taiwo-adewale/ecommerce-admin",
  "mithunjmistry/ecommerce-React-Redux-Laravel",
  "cktang88/spaceboard",
  "seeden/react-g-analytics",
  "DulanjaliSenarathna/react-chat-app",
  "themisvaltinos/Auction-Website",
  "Govind783/react-e-commerce-",
  "damianstone/toogether-mobile",
  "neiker/analytics-react-native",
  "YashMarmat/FullStack_Ecommerce_App",
  "ximing/weditor",
  "offlegacy/event-tracker",
  "FLiotta/Yasei",
  "gianlucajahn/react-ecommerce-store",
  "dch133/Social-Media-App",
  "Mohitur669/Realtime-Collaborative-Code-Editor",
  "Qeagle/reporter-engine",
  "HosseinNamvar/bitex",
  "coding-with-chaim/react-video-chat",
  "concrnt/concrnt-world",
  "etesync/etesync-notes",
  "vivekkakadiya/Organica",
  "jagjot26/faeshare",
  "UsamaSarwar/reactnative-ecommerce-charlie",
  "ReactNativeSchool/react-native-social-media-app",
  "shubham1710/MERN-E-Commerce",
  "yTakkar/MERN-Social-Network",
];

interface PackageJson {
  name: string;
  version: string;
}

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageDirectory = resolve(scriptDirectory, "..");
const workspaceRootDirectory = resolve(packageDirectory, "..", "..");
const regressionOutputDirectory = join(packageDirectory, REGRESSION_OUTPUT_DIRECTORY_NAME);
const reactReviewApiDirectory = join(homedir(), REACT_REVIEW_API_RELATIVE_PATH);
const reactReviewEnvLocalPath = join(reactReviewApiDirectory, ".env.local");

const formatErrorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

const captureGitHubAuthToken = (): string => {
  try {
    const rawToken = execFileSync("gh", ["auth", "token"], { encoding: "utf-8" }).trim();
    if (!rawToken) {
      throw new Error("`gh auth token` returned an empty string");
    }
    return rawToken;
  } catch (gitHubAuthError) {
    throw new Error(
      [
        "Failed to obtain a GitHub token via `gh auth token`.",
        "GitHub returns 403 for tarball downloads without authentication, which makes the test pointless.",
        "Run `gh auth login` first and retry.",
        `Underlying error: ${formatErrorMessage(gitHubAuthError)}`,
      ].join("\n"),
    );
  }
};

const ensureReactReviewWorkspaceIsReady = (): void => {
  if (!existsSync(reactReviewApiDirectory)) {
    throw new Error(
      [
        `Missing react-review checkout at \`${reactReviewApiDirectory}\`.`,
        "Clone the sibling repo with `git clone https://github.com/millionco/react-review ~/Developer/react-review`.",
      ].join("\n"),
    );
  }
  if (!existsSync(reactReviewEnvLocalPath)) {
    throw new Error(
      [
        `Missing \`${reactReviewEnvLocalPath}\`.`,
        "The sandbox test needs Vercel credentials. Run `vercel env pull` inside",
        `\`${reactReviewApiDirectory}\` first.`,
      ].join("\n"),
    );
  }
};

const readPackageJson = (): PackageJson =>
  JSON.parse(readFileSync(join(packageDirectory, "package.json"), "utf-8")) as PackageJson;

const buildReactDoctorPackage = (): void => {
  console.log("[regression] Building react-doctor...");
  execFileSync("pnpm", ["--filter", "react-doctor", "build"], {
    stdio: "inherit",
    cwd: workspaceRootDirectory,
  });
};

const packReactDoctorTarball = (): string => {
  mkdirSync(regressionOutputDirectory, { recursive: true });
  console.log(`[regression] Packing tarball into ${regressionOutputDirectory}...`);
  execFileSync(
    "pnpm",
    ["--filter", "react-doctor", "pack", "--pack-destination", regressionOutputDirectory],
    {
      stdio: "inherit",
      cwd: workspaceRootDirectory,
    },
  );

  const packageMetadata = readPackageJson();
  const expectedTarballName = `react-doctor-${packageMetadata.version}.tgz`;
  const expectedTarballPath = join(regressionOutputDirectory, expectedTarballName);
  if (!existsSync(expectedTarballPath)) {
    throw new Error(
      `Expected tarball \`${expectedTarballPath}\` to exist after \`pnpm pack\` but it was not produced.`,
    );
  }
  const tarballStats = statSync(expectedTarballPath);
  if (!tarballStats.isFile() || tarballStats.size === 0) {
    throw new Error(`Tarball \`${expectedTarballPath}\` exists but is empty or not a file.`);
  }
  return expectedTarballPath;
};

const parseSampleSizeOverride = (rawSampleSize: string | undefined): number => {
  if (rawSampleSize === undefined || rawSampleSize === "") return DEFAULT_FLEET_SAMPLE_SIZE;
  if (rawSampleSize.toLowerCase() === "all") return REGRESSION_FLEET.length;
  const parsedSampleSize = Number.parseInt(rawSampleSize, 10);
  if (!Number.isFinite(parsedSampleSize) || parsedSampleSize <= 0) {
    throw new Error(
      `Invalid REACT_DOCTOR_REGRESSION_SAMPLE value: \`${rawSampleSize}\`. Use a positive integer or \`all\`.`,
    );
  }
  return Math.min(parsedSampleSize, REGRESSION_FLEET.length);
};

const resolveRegressionRepos = (): readonly string[] => {
  const userProvidedRepos = process.env.REACT_DOCTOR_TEST_REPOS;
  if (userProvidedRepos && userProvidedRepos.trim()) {
    const explicitRepos = userProvidedRepos
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean);
    if (explicitRepos.length > 0) return explicitRepos;
  }
  const sampleSize = parseSampleSizeOverride(process.env.REACT_DOCTOR_REGRESSION_SAMPLE);
  return REGRESSION_FLEET.slice(0, sampleSize);
};

const runReactReviewSandboxTest = (
  tarballAbsolutePath: string,
  gitHubAuthToken: string,
  testRepos: readonly string[],
): void => {
  if (!isAbsolute(tarballAbsolutePath)) {
    throw new Error(`Expected absolute tarball path, got \`${tarballAbsolutePath}\``);
  }
  console.log(
    `[regression] Driving react-review test against ${testRepos.length} repo(s): ${testRepos.join(", ")}`,
  );
  execFileSync("pnpm", ["test"], {
    stdio: "inherit",
    cwd: reactReviewApiDirectory,
    env: {
      ...process.env,
      GITHUB_TOKEN: gitHubAuthToken,
      REACT_DOCTOR_SPECIFIERS: tarballAbsolutePath,
      REACT_DOCTOR_TEST_REPOS: testRepos.join(","),
    },
  });
};

const runRegression = (): void => {
  ensureReactReviewWorkspaceIsReady();
  const gitHubAuthToken = captureGitHubAuthToken();
  buildReactDoctorPackage();
  const tarballAbsolutePath = packReactDoctorTarball();
  console.log(`[regression] Tarball: ${tarballAbsolutePath}`);
  const testRepos = resolveRegressionRepos();
  runReactReviewSandboxTest(tarballAbsolutePath, gitHubAuthToken, testRepos);
};

runRegression();
